### ISSUE TITLE
What are the min and max versions of VSCode that are compatible with this extension?

### ISSUE THREAD

**Issue by bluebeag** [salesforce/salesforcedx-vscode-mobile#37]
![image](https://github.com/salesforce/salesforcedx-vscode-mobile/assets/25390566/1247f840-36f3-4fec-bee9-53f622e2e5db)

**Comment by dbreese** [comment]
Ah, It might be compatible with older versions, so we picked a somewhat recent version, 1.77.0 (March 2023) as the base. 1.70.1 is from August 2022. There really isn't anything precluding us from supporting older versions of VSCode I dont think, at least not with this version.

**Comment by bluebeag** [comment]
Thank you for the update! I’ll update my VSCode version, try again and let you know.Do you know if it’s required to have LWC to make offline object creation work? Also, with Salesforce Mobile App Plus, the documentation says standard metadata features are supported offline. Are Object creation and flows part of this or do I need to create an LWC to say, create a new Work Order? -Kevin JuddOn Jul 7, 2023, at 3:52 PM, dbreese ***@***.***> wrote:﻿
Ah, It might be compatible with older versions, so we picked a somewhat recent version, 1.77.0 (March 2023) as the base. 1.70.1 is from August 2022. There really isn't anything precluding us from supporting older versions of VSCode I dont think, at least not with this version.

**Comment by dbreese** [comment]
Probably best to post questions such as these in the Trailblazer community as you can get a much wider response, perhaps in the [LWC Offline for Salesforce App Plus](https://trailhead.salesforce.com/trailblazer-community/groups/0F94S000000kJh0SAE) is the best for these questions.

I am not 100% sure if Salesforce App will support object creation offline, except from an LWC quick action. Flows are only supported in Field Service mobile app, so you wouldnt be able to utilize that in Salesforce App, but if you are using Field Service, you can [reference the docs here ](https://help.salesforce.com/s/articleView?id=sf.mfs_flow.htm&type=5)to create a flow.

You can also see some examples of object creation in the [Offline App Starter Kit repo here](https://github.com/salesforce/offline-app-developer-starter-kit).

**Comment by dbreese** [comment]
Upgrading your version of VS Code should fix the issue as [in our package we specify a minimum version of 1.77.0](https://github.com/salesforce/salesforcedx-vscode-mobile/blob/main/package.json#L8). Please let us know if it still will not install after upgrading and we can re-open this issue.

**Comment by bluebeag** [comment]
Good suggestion. It’s somewhat frustrating posting in the Trailblazer community because I either get misinformation or little information regarding my posts. I’m not using Field Service, so that’s out.  Thanks for your response though, it points me in a closer direction. I was able to install the extension after upgrading VSCode to the latest version. Thank you! -Kevin JuddOn Jul 9, 2023, at 9:12 AM, dbreese ***@***.***> wrote:﻿
Probably best to post questions such as these in the Trailblazer community as you can get a much wider response, perhaps in the LWC Offline for Salesforce App Plus is the best for these questions.
I am not 100% sure if Salesforce App will support object creation offline, except from an LWC quick action. Flows are only supported in Field Service mobile app, so you wouldnt be able to utilize that in Salesforce App, but if you are using Field Service, you can reference the docs here to create a flow.
You can also see some examples of object creation in the Offline App Starter Kit repo here.
